name: Build and Deploy Storybook
on:
  push:
    branch: feature/table-deployment
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          npm install
          npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs # The branch the action should deploy to. Change as required on Dev
          FOLDER: storybook-static
          CLEAN: true
          TARGET_FOLDER: storybook-static
